### ISSUE TITLE
Draw diagrams for strategy archetypes

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/ml-paper#11]
Build on what is currently the `images` branch.

**Comment by drvinceknight** [comment]
I tagged the wrong issue on #12.

**Comment by marcharper** [comment]
* The HMM probabilities should be probabilities
* ANN diagram is a little misleading since there are actually more nodes than depicted (maybe some ellipses could help)
* (minor) For ANN we should have C or D on the right hand side

**Comment by drvinceknight** [comment]
> The HMM probabilities should be probabilities

They are?  There's two row of outputs: the first is all the "things": so C and D and a list of the states, and under that I've included probabilities. I've got an idea to fix this.

> ANN diagram is a little misleading since there are actually more nodes than depicted (maybe some ellipses could help)

Yeah I was wondering about this. I'll try the ellipsis!

> (minor) For ANN we should have C or D on the right hand side

Similarly for Lookerup. I'll fix.
