### ISSUE TITLE
Better colormaps for heatmaps

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/ml-paper#6]
Discussed on #4 

`"gnuplot2"`:

We can see the 0s (S) in black, the 1s (P) in blue, the 3s (R) in pink and the 5s (T) in white.

![download](https://user-images.githubusercontent.com/2131546/27908903-0617f786-6246-11e7-84ff-f526d90d9b74.png)

`"gist_earth"`:

We can see the 0s (S) in black, the 1s (P) in blue, the 3s (R) in green and the 5s (T) in white.

![download 16](https://user-images.githubusercontent.com/2131546/27908915-15e44976-6246-11e7-9b41-53c453058e45.png)

Let me know what you think @marcharper :)

**Comment by meatballs** [comment]
I reckon the gnuplot version is better - it's much clearer to see what the order is.

In the gist_earth version, it's not clear to me that brown would be considered a 'hotter' colour than green.

**Comment by marcharper** [comment]
I agree with @meatballs but the pink is a bit much. Is it better than the original? 0 and 1 are a little hard to distinguish in the viridis plot.

**Comment by drvinceknight** [comment]
Here's the original:

![download 17](https://user-images.githubusercontent.com/2131546/27909630-8129160a-6249-11e7-8d94-bbf9f16df443.png)

I'm easy but by `gist_earth` or `gnu_plot` we are moving away from `virids` (the default) which is known to be good in terms of progression of colors and a number of other properties. So it might be a question as to whether or not we want to clearly identify RPST. `gist_earth` and `gnu_plot2` aren't reknowned color maps but seem to have 4 clear colors which is what RPST identification wants (I think).

**Comment by drvinceknight** [comment]
The main "problem" is that the difference between 1 (P) and 0 (S) is not as evident with `viridis` as opposed to the others.

**Comment by marcharper** [comment]
Yeah viridis seems better still. Thanks for looking into this!
