### ISSUE TITLE
Include heatmap of cooperation rates 

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/ml-paper#7]
Would be nice to include images like https://github.com/Axelrod-Python/AxelrodExamples/blob/master/strategies/TF1.md which clearly show the handshake.

These need to be "re run" with the list of players used (available in `src/players`). If possible can we include a `src/cooperation_rates.py` that generates the data and then we create the plots in `main.ipynb`. (I'm happy to do this.)

**Comment by drvinceknight** [comment]
I'll pick this up next. (Just taking the :dog: for a walk :))

**Comment by drvinceknight** [comment]
Data is running for this (from the `cooperation-heatmap` branch). 

FYI, I took a look at the code on Axelrod-examples repo and felt it was better to rewrite for this purpose:

- Have done it with a spatial tournament (to take advantage of the parallelisation);
- Have computed the arrays with a line of pandas

It didn't take me long at all and felt better to keep things a bit more concise for the paper.

I'm doing this for 10k repetitions which feels right. But I can push that to 50k after.

**Comment by drvinceknight** [comment]
Will open a PR once I've got the data back.

**Comment by marcharper** [comment]
For the noisy heatmaps the base rate should be at most 95% but the plots in the paper show 100%.

**Comment by marcharper** [comment]
Also viridis makes for a non-aesthetically pleasing heatmap. Try using [plasma](https://matplotlib.org/users/colormaps.html) or RdBu, we only need one variation dimension to go for [0, 1].

(I'm also updating the examples repository images).

**Comment by drvinceknight** [comment]
> For the noisy heatmaps the base rate should be at most 95% but the plots in the paper show 100%.

I did not draw these heatmaps in a noisy environment. I thought about it but felt that we were trying to draw a representation of the strategy and not necessarily the strategy in an environment. I still think it's the way to go (this is a "fingerprint" so it should be a constant) but perhaps we should include a sentence clarifying that?

> Also viridis makes for a non-aesthetically pleasing heatmap. Try using plasma or RdBu, we only need one variation dimension to go for [0, 1].

Will do.
