### ISSUE TITLE
Draw diagrams of FSMs

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/ml-paper#9]
Perhaps just the one (the best performing one) or perhaps two: the best in standard and the best in noise.

Similar to diagrams for the moran paper, eg: https://github.com/Axelrod-Python/axelrod-moran/blob/master/tex/fsm_one.tex

**Comment by drvinceknight** [comment]
@Nikoleta-v3 if you could draw the FSM diagrams for:

- Evolved FSM 16: https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/finite_state_machines.py#L461
- Evolved FSM 16 Noise 05: https://github.com/Axelrod-Python/Axelrod/blob/master/axelrod/strategies/finite_state_machines.py#L519

**Comment by Nikoleta-v3** [comment]
Great I will take over this.

**Comment by drvinceknight** [comment]
Fantastic, thank you. :+1:

**Comment by drvinceknight** [comment]
Given that they're both 16 state FSM and the difference is just that one is trained for noise I'd suggest that you get the layout for one right and then just use the same layout for the noisy one. That way it should be clear to see the differences which we could choose to discuss.

**Comment by drvinceknight** [comment]
I tagged the wrong issue on #12 (which closed this issue).

**Comment by marcharper** [comment]
@Nikoleta-v3 @drvinceknight 

Some of the noisy FSM arcs are missing labels (look at state 1 and 2 for example).

**Comment by drvinceknight** [comment]
> Some of the noisy FSM arcs are missing labels (look at state 1 and 2 for example).

I thought so too but they're not missing. On #17 I wrote:

> FYI, my gpu/screen wasn't showing all the transitions on the complete pdf (just because of the quantity of vectors we're now putting in there with all the plots etc). I doubled checked and it's all fine.

Basically our pdf is just so full of vectors that it's not displaying some things - or perhaps LaTeX can't keep track of everything? - (if you build the pdfs for the fsms themselves everything is there).

Let's keep this issue open and see what the paper looks like when we're ready. One option could be to draw the FSM diagrams as rastered images (png etc) and just include those directly.

**Comment by drvinceknight** [comment]
It could also be the layout... Because some of the things overlap it might be struggling... I'll have a play around.
